# Generated by Django 5.2.8 on 2025-12-10 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='skill_thumbnails/')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('youtube', 'YouTube Tutorial'), ('pdf', 'PDF Document')], max_length=20)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='materials/pdfs/')),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('duration', models.CharField(blank=True, help_text="e.g., '15 minutes' or '10 pages'", max_length=50)),
                ('is_preview', models.BooleanField(default=False, help_text='Free preview material')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.skillcategory')),
            ],
            options={
                'ordering': ['skill_category', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='materials.worksubmission')),
            ],
            options={
                'verbose_name_plural': 'Mentor Feedback',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for lifetime access', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=100)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Access Records',
                'unique_together': {('user', 'skill_category')},
            },
        ),
    ]
