# Generated by Django 5.2.8 on 2025-12-12 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='skill_category',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='mentorfeedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.RemoveField(
            model_name='mentorfeedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='worksubmission',
            name='skill_category',
        ),
        migrations.RemoveField(
            model_name='worksubmission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon',
            field=models.CharField(default='fa-book', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.skillcategory'),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorfeedback',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='file',
            field=models.FileField(upload_to='work_submissions/'),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('video', 'YouTube Video'), ('pdf', 'PDF Document')], max_length=10)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='materials/pdfs/')),
                ('access_level', models.CharField(choices=[('basic', 'Basic - Free'), ('enterprise', 'Enterprise - KSh 100'), ('premium', 'Premium - KSh 200')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.skillcategory')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mpesa_code', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('basic', 'Basic - Free'), ('enterprise', 'Enterprise - KSh 100'), ('premium', 'Premium - KSh 200')], default='basic', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Skill Access',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='UserAccess',
        ),
    ]
