# Generated by Django 5.2.8 on 2025-12-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_useraccess_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorfeedback',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
